using System; using System.Collections.Generic; using System.Diagnostics; using System.Drawing; using System.IO; using System.Net; using System.Text; using System.Text.RegularExpressions; using System.Windows.Forms;
namespace AutosurBuscador {
static class UpdateManager {
 public const string AppVersion="1.2.5";
 const string ApiUrl="https://api.github.com/repos/juancarlosamarante94-alt/Buscador-Autosur/releases/latest";
 const string ReleasesUrl="https://github.com/juancarlosamarante94-alt/Buscador-Autosur/releases";
 static string Q(string value){return "'"+value.Replace("'","''")+"'";}
 public static void Check(Form owner,Button button){button.Enabled=false;Cursor old=owner.Cursor;owner.Cursor=Cursors.WaitCursor;try{ServicePointManager.SecurityProtocol=(SecurityProtocolType)3072;string json;using(var web=new WebClient()){web.Headers[HttpRequestHeader.UserAgent]="Buscador-Autosur/"+AppVersion;json=web.DownloadString(ApiUrl);}var tag=Regex.Match(json,"\\\"tag_name\\\"\\s*:\\s*\\\"v?([^\\\"]+)\\\"");if(!tag.Success)throw new Exception("GitHub no devolvio un numero de version valido.");Version latest,current;if(!Version.TryParse(tag.Groups[1].Value,out latest)||!Version.TryParse(AppVersion,out current))throw new Exception("No se pudo comparar la version instalada.");if(latest<=current){MessageBox.Show(owner,"Ya tenes la ultima version ("+AppVersion+").","Actualizaciones",MessageBoxButtons.OK,MessageBoxIcon.Information);return;}var asset=Regex.Match(json,"\\\"browser_download_url\\\"\\s*:\\s*\\\"([^\\\"]*Buscador_Autosur_Actualizacion\\.zip)\\\"");if(!asset.Success){Process.Start(ReleasesUrl);MessageBox.Show(owner,"Hay una version nueva, pero el paquete automatico aun no esta disponible. Se abrio la pagina de descargas.","Actualizaciones",MessageBoxButtons.OK,MessageBoxIcon.Information);return;}if(MessageBox.Show(owner,"Hay una nueva version ("+latest+"). ¿Queres descargarla e instalarla ahora?","Actualizacion disponible",MessageBoxButtons.YesNo,MessageBoxIcon.Question)!=DialogResult.Yes)return;string root=Path.Combine(Path.GetTempPath(),"Buscador_Autosur_Update_"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(root);string zip=Path.Combine(root,"actualizacion.zip");using(var web=new WebClient()){web.Headers[HttpRequestHeader.UserAgent]="Buscador-Autosur/"+AppVersion;web.DownloadFile(asset.Groups[1].Value,zip);}string extract=Path.Combine(root,"contenido");string script=Path.Combine(root,"actualizar.ps1");string installer=Path.Combine(extract,"Buscador_VIN_Instalable","Instalar.ps1");File.WriteAllText(script,"Start-Sleep -Seconds 2\r\nExpand-Archive -LiteralPath "+Q(zip)+" -DestinationPath "+Q(extract)+" -Force\r\n& "+Q(installer)+"\r\n",Encoding.UTF8);Process.Start(new ProcessStartInfo{FileName="powershell.exe",Arguments="-NoProfile -ExecutionPolicy Bypass -File \""+script+"\"",UseShellExecute=true});Application.Exit();}catch(WebException){MessageBox.Show(owner,"No se pudo consultar GitHub. Comproba la conexion a Internet e intenta nuevamente.","Actualizaciones",MessageBoxButtons.OK,MessageBoxIcon.Warning);}catch(Exception ex){MessageBox.Show(owner,"No se pudo completar la actualizacion.\n\n"+ex.Message,"Actualizaciones",MessageBoxButtons.OK,MessageBoxIcon.Error);}finally{owner.Cursor=old;button.Enabled=true;}}
}
static class Tools {
 public static string D(string s){return Encoding.UTF8.GetString(Convert.FromBase64String(s));}
 public static string N(string s){if(String.IsNullOrWhiteSpace(s))return "";var b=new StringBuilder();foreach(char c in s.ToUpperInvariant())if(Char.IsLetterOrDigit(c))b.Append(c);return b.ToString();}
 public static DataGridView Grid(string[] n,int[] w){var g=new DataGridView{Dock=DockStyle.Fill,ReadOnly=true,AllowUserToAddRows=false,AllowUserToDeleteRows=false,AllowUserToOrderColumns=true,MultiSelect=false,SelectionMode=DataGridViewSelectionMode.CellSelect,BackgroundColor=Color.White,AutoGenerateColumns=false,AutoSizeColumnsMode=DataGridViewAutoSizeColumnsMode.None,AutoSizeRowsMode=DataGridViewAutoSizeRowsMode.None,ScrollBars=ScrollBars.Both,ColumnHeadersHeight=36,ColumnHeadersHeightSizeMode=DataGridViewColumnHeadersHeightSizeMode.DisableResizing};g.RowTemplate.Height=31;g.ColumnHeadersDefaultCellStyle.Font=new Font("Segoe UI",9.5f,FontStyle.Bold);for(int i=0;i<n.Length;i++)g.Columns.Add(new DataGridViewTextBoxColumn{Name=n[i],HeaderText=n[i],Width=w[i],MinimumWidth=70,AutoSizeMode=DataGridViewAutoSizeColumnMode.None,SortMode=DataGridViewColumnSortMode.NotSortable});return g;}
 public static void Copy(DataGridView g,Label s,DataGridViewCellEventArgs e){if(e.RowIndex<0||e.ColumnIndex<0)return;object o=g.Rows[e.RowIndex].Cells[e.ColumnIndex].Value;string v=o==null?"":o.ToString();if(v.Length==0){s.Text="La celda seleccionada esta vacia.";return;}Clipboard.SetText(v);s.Text=g.Columns[e.ColumnIndex].HeaderText+" copiado: "+v;}
 public static TextBox Search(Control p,EventHandler changed,out Button clear){var x=new Panel{Dock=DockStyle.Top,Height=62,BackColor=Color.White};p.Controls.Add(x);x.Controls.Add(new Label{Text="Buscar",AutoSize=true,Font=new Font("Segoe UI",10f,FontStyle.Bold),Location=new Point(14,22)});var b=new TextBox{Font=new Font("Segoe UI",15f),Location=new Point(82,14),Anchor=AnchorStyles.Top|AnchorStyles.Left|AnchorStyles.Right};x.Controls.Add(b);var localClear=new Button{Text="Limpiar",Width=82,Height=34,Anchor=AnchorStyles.Top|AnchorStyles.Right};clear=localClear;x.Controls.Add(localClear);x.Resize+=delegate{b.Width=Math.Max(150,x.Width-190);localClear.Location=new Point(x.Width-96,13);};b.TextChanged+=changed;return b;}
}
class GridHost:Panel {
 public DataGridView Grid;public HScrollBar H=new HScrollBar();public VScrollBar V=new VScrollBar();
 public GridHost(DataGridView g){Grid=g;Dock=DockStyle.Fill;Padding=new Padding(0);g.ScrollBars=ScrollBars.None;g.Dock=DockStyle.Fill;H.Dock=DockStyle.Bottom;H.Height=19;V.Dock=DockStyle.Right;V.Width=19;Controls.Add(g);Controls.Add(V);Controls.Add(H);H.Scroll+=delegate(object o,ScrollEventArgs e){try{g.HorizontalScrollingOffset=e.NewValue;}catch{}};V.Scroll+=delegate(object o,ScrollEventArgs e){if(g.Rows.Count>0){int n=Math.Min(e.NewValue,g.Rows.Count-1);try{g.FirstDisplayedScrollingRowIndex=n;}catch{}}};g.Scroll+=delegate{SyncFromGrid();};Resize+=delegate{UpdateBars();};}
 public void UpdateBars(){if(Grid.IsDisposed)return;int total=Grid.RowHeadersVisible?Grid.RowHeadersWidth:0;foreach(DataGridViewColumn c in Grid.Columns)if(c.Visible)total+=c.Width;int view=Math.Max(1,Grid.ClientSize.Width);H.Minimum=0;H.LargeChange=view;H.SmallChange=40;H.Maximum=Math.Max(0,total-1);H.Enabled=total>view;int maxH=Math.Max(0,H.Maximum-H.LargeChange+1);if(H.Value>maxH)H.Value=maxH;int rows=Grid.Rows.Count;int shown=Math.Max(1,(Grid.ClientSize.Height-Grid.ColumnHeadersHeight)/Math.Max(1,Grid.RowTemplate.Height));V.Minimum=0;V.LargeChange=shown;V.SmallChange=1;V.Maximum=Math.Max(0,rows-1);V.Enabled=rows>shown;int maxV=Math.Max(0,V.Maximum-V.LargeChange+1);if(V.Value>maxV)V.Value=maxV;}
 void SyncFromGrid(){if(Grid.HorizontalScrollingOffset>=H.Minimum&&Grid.HorizontalScrollingOffset<=Math.Max(H.Minimum,H.Maximum-H.LargeChange+1))H.Value=Grid.HorizontalScrollingOffset;if(Grid.Rows.Count>0){int r=Grid.FirstDisplayedScrollingRowIndex;int max=Math.Max(V.Minimum,V.Maximum-V.LargeChange+1);if(r>=V.Minimum&&r<=max)V.Value=r;}}
}
class Vehicle {public string[] V;public string P,M,E;}
class VehiclePage:UserControl {
 List<Vehicle>d=new List<Vehicle>();DataGridView g;GridHost host;TextBox q;Label s=new Label();Timer t=new Timer();
 public VehiclePage(){Dock=DockStyle.Fill;Padding=new Padding(14);BackColor=Color.FromArgb(243,245,247);var p=new Panel{Dock=DockStyle.Fill};Controls.Add(p);p.Controls.Add(new Label{Text="Usa las barras inferior y lateral para desplazarte. Doble clic copia cualquier dato.",Dock=DockStyle.Bottom,Height=28,ForeColor=Color.DimGray});string[] n={"Patente","Modelo","Motor","VIN","Descripcion","Color","Serie"};int[]w={110,140,200,200,430,150,120};g=Tools.Grid(n,w);g.CellDoubleClick+=delegate(object o,DataGridViewCellEventArgs e){Tools.Copy(g,s,e);};host=new GridHost(g);p.Controls.Add(host);s.Dock=DockStyle.Top;s.Height=29;s.Font=new Font("Segoe UI",9.5f,FontStyle.Bold);p.Controls.Add(s);Button c;q=Tools.Search(p,delegate{t.Stop();t.Start();},out c);c.Click+=delegate{q.Clear();q.Focus();};t.Interval=80;t.Tick+=delegate{t.Stop();Run();};LoadData();}
 void LoadData(){string path=Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"vehiculos.dat");if(!File.Exists(path)){s.Text="No se encontro vehiculos.dat";return;}foreach(string line in File.ReadLines(path,Encoding.UTF8)){string[]a=line.Split('\t');if(a.Length!=7)continue;string[]v=new string[7];for(int i=0;i<7;i++)v[i]=Tools.D(a[i]);d.Add(new Vehicle{V=v,P=Tools.N(v[3]),M=Tools.N(v[1]),E=Tools.N(v[6])});}s.Text="Listo. "+d.Count.ToString("N0")+" vehiculos cargados.";}
 void Run(){string x=Tools.N(q.Text);g.Rows.Clear();if(x.Length==0){s.Text="Escribi una patente, un modelo o un motor para comenzar.";host.UpdateBars();return;}g.SuspendLayout();int c=0;foreach(Vehicle v in d)if(v.P.Contains(x)||v.M.Contains(x)||v.E.Contains(x)){g.Rows.Add(v.V[3],v.V[1],v.V[6],v.V[0],v.V[2],v.V[4],v.V[5]);if(++c==500)break;}g.ResumeLayout();host.UpdateBars();s.Text=c==0?"No se encontraron coincidencias.":c==500?"Se muestran las primeras 500 coincidencias. Escribi un poco mas.":c+" coincidencia(s).";}
}
class Client {public string[]V;public string N,D,C;}
class ClientPage:UserControl {
 List<Client>d=new List<Client>();DataGridView g;GridHost host;TextBox q;Label s=new Label();Timer t=new Timer();
 static readonly string[] Names={"Indice","Nombre","Apellido","CUIT/CUIL","Documento","Categoria","Pais","Codigo postal","Localidad","Direccion","Telefono","Telefono laboral","Celular laboral","Fecha de nacimiento","Estado civil","Email"};
 public ClientPage(){Dock=DockStyle.Fill;Padding=new Padding(14);BackColor=Color.FromArgb(243,245,247);var p=new Panel{Dock=DockStyle.Fill};Controls.Add(p);p.Controls.Add(new Label{Text="Busca por nombre, apellido, DNI o CUIL. Usa las barras inferior y lateral para desplazarte.",Dock=DockStyle.Bottom,Height=28,ForeColor=Color.DimGray});int[]w={100,210,150,140,125,120,110,120,165,290,135,145,145,150,125,240};g=Tools.Grid(Names,w);g.CellDoubleClick+=delegate(object o,DataGridViewCellEventArgs e){Tools.Copy(g,s,e);};host=new GridHost(g);p.Controls.Add(host);s.Dock=DockStyle.Top;s.Height=29;s.Font=new Font("Segoe UI",9.5f,FontStyle.Bold);p.Controls.Add(s);Button c;q=Tools.Search(p,delegate{t.Stop();t.Start();},out c);c.Click+=delegate{q.Clear();q.Focus();};t.Interval=80;t.Tick+=delegate{t.Stop();Run();};LoadData();}
 void LoadData(){string path=Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"clientes.dat");if(!File.Exists(path)){s.Text="No se encontro clientes.dat";return;}foreach(string line in File.ReadLines(path,Encoding.UTF8)){string[]a=line.Split('\t');if(a.Length!=16)continue;string[]v=new string[16];for(int i=0;i<16;i++)v[i]=Tools.D(a[i]);d.Add(new Client{V=v,N=Tools.N(v[1]+" "+v[2]),C=Tools.N(v[3]),D=Tools.N(v[4])});}s.Text="Listo. "+d.Count.ToString("N0")+" clientes cargados.";}
 void Run(){string x=Tools.N(q.Text);g.Rows.Clear();if(x.Length==0){s.Text="Escribi un nombre, apellido, DNI o CUIL para comenzar.";host.UpdateBars();return;}g.SuspendLayout();int c=0;foreach(Client v in d)if(v.N.Contains(x)||v.D.Contains(x)||v.C.Contains(x)){g.Rows.Add(v.V);if(++c==500)break;}g.ResumeLayout();host.UpdateBars();s.Text=c==0?"No se encontraron coincidencias.":c==500?"Se muestran las primeras 500 coincidencias. Escribi un poco mas.":c+" coincidencia(s).";}
}
public class MainForm:Form {public MainForm(){Text="Buscador Autosur";string ip=Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"icono_autosur.ico");if(File.Exists(ip))Icon=new Icon(ip);StartPosition=FormStartPosition.CenterScreen;MinimumSize=new Size(940,560);Size=new Size(1280,760);Font=new Font("Segoe UI",10f);var layout=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=1,RowCount=2,Margin=new Padding(0),Padding=new Padding(0)};layout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100f));layout.RowStyles.Add(new RowStyle(SizeType.Absolute,43f));layout.RowStyles.Add(new RowStyle(SizeType.Percent,100f));var bar=new Panel{Dock=DockStyle.Fill,BackColor=Color.White,Padding=new Padding(10,5,10,4),Margin=new Padding(0)};var version=new Label{Text="Buscador Autosur - Version "+UpdateManager.AppVersion,Dock=DockStyle.Left,AutoSize=false,Width=260,TextAlign=ContentAlignment.MiddleLeft,Font=new Font("Segoe UI",9.5f,FontStyle.Bold)};var update=new Button{Text="Buscar actualizaciones",Dock=DockStyle.Right,Width=185};update.Click+=delegate{UpdateManager.Check(this,update);};bar.Controls.Add(version);bar.Controls.Add(update);var tabs=new TabControl{Dock=DockStyle.Fill,Font=new Font("Segoe UI",11f,FontStyle.Bold),Margin=new Padding(0)};var a=new TabPage("Vehiculos");a.Controls.Add(new VehiclePage());var b=new TabPage("Clientes");b.Controls.Add(new ClientPage());var c=new TabPage("Turnero");c.Controls.Add(new TurneroPage());tabs.TabPages.Add(a);tabs.TabPages.Add(b);tabs.TabPages.Add(c);layout.Controls.Add(bar,0,0);layout.Controls.Add(tabs,0,1);Controls.Add(layout);}[STAThread]public static void Main(){Application.EnableVisualStyles();Application.SetCompatibleTextRenderingDefault(false);Application.Run(new MainForm());}}
}
