namespace AutosurBuscador {
using System; using System.Collections.Generic; using System.Drawing; using System.Drawing.Printing; using System.IO; using System.Linq; using System.Text; using System.Text.RegularExpressions; using System.Windows.Forms;
using UglyToad.PdfPig; using UglyToad.PdfPig.Content;

class AgendaWord { public string Text; public double X,Y; }
class AgendaLine { public double Y; public List<AgendaWord> Words=new List<AgendaWord>(); public string Text { get { Words.Sort(delegate(AgendaWord a,AgendaWord b){return a.X.CompareTo(b.X);}); return String.Join(" ",Words.Select(x=>x.Text).ToArray()); } } }
class Appointment { public string Fecha="",Hora="",Cliente="",Telefono="",Modelo="",Patente="",Chasis="",Motor="",Servicio=""; }

public class TurneroPage:UserControl {
 List<Appointment> turns=new List<Appointment>(); DataGridView grid; GridHost host; Label status=new Label(); PrintDocument printer=new PrintDocument(); int printIndex;
 public TurneroPage(){Dock=DockStyle.Fill;Padding=new Padding(14);BackColor=Color.FromArgb(243,245,247);BuildUi();printer.DefaultPageSettings.Landscape=false;printer.DefaultPageSettings.Margins=new Margins(30,30,30,30);SetA4();printer.PrintPage+=PrintPage;}
 void BuildUi(){var top=new Panel{Dock=DockStyle.Top,Height=58,BackColor=Color.White};Controls.Add(top);var load=new Button{Text="Cargar PDF del turnero",Location=new Point(14,12),Size=new Size(180,34)};var preview=new Button{Text="Vista previa",Location=new Point(205,12),Size=new Size(115,34),Enabled=false};var print=new Button{Text="Imprimir turnero",Location=new Point(331,12),Size=new Size(145,34),Enabled=false};var export=new Button{Text="Exportar PDF",Location=new Point(487,12),Size=new Size(130,34),Enabled=false};top.Controls.Add(load);top.Controls.Add(preview);top.Controls.Add(print);top.Controls.Add(export);status.Text="Carga el PDF de la agenda nueva. Se conservaran solamente los turnos Renault.";status.Dock=DockStyle.Top;status.Height=31;status.Font=new Font("Segoe UI",9.5f,FontStyle.Bold);Controls.Add(status);string[] n={"Fecha","Hora","Cliente","Telefono","Modelo Renault","Patente","Chasis","Motor","Servicio"};int[]w={90,70,220,130,260,100,175,80,430};grid=Tools.Grid(n,w);grid.CellDoubleClick+=delegate(object o,DataGridViewCellEventArgs e){Tools.Copy(grid,status,e);};host=new GridHost(grid);Controls.Add(host);host.BringToFront();status.BringToFront();top.BringToFront();load.Click+=delegate{LoadPdf();preview.Enabled=print.Enabled=export.Enabled=turns.Count>0;};preview.Click+=delegate{ShowPreview();};print.Click+=delegate{PrintNow();};export.Click+=delegate{ExportPdf();};}
 void LoadPdf(){using(var dialog=new OpenFileDialog{Filter="Archivos PDF (*.pdf)|*.pdf",Title="Seleccionar turnero nuevo"}){if(dialog.ShowDialog()!=DialogResult.OK)return;try{Cursor=Cursors.WaitCursor;status.Text="Leyendo y filtrando turnos Renault...";Application.DoEvents();turns=Extract(dialog.FileName);CompleteMotors();ShowRows();status.Text=turns.Count+" turno(s) Renault encontrados. Los Nissan y horarios disponibles fueron excluidos.";}catch(Exception ex){turns.Clear();grid.Rows.Clear();MessageBox.Show("No se pudo leer el PDF.\n\n"+ex.Message,"Turnero",MessageBoxButtons.OK,MessageBoxIcon.Error);status.Text="No se pudo procesar el archivo.";}finally{Cursor=Cursors.Default;}}}
 List<Appointment> Extract(string path){var all=new List<AgendaWord>();double offset=0;string date="";using(PdfDocument doc=PdfDocument.Open(path)){int pageNo=0;foreach(Page page in doc.GetPages()){pageNo++;var pageWords=new List<AgendaWord>();double actionCutoff=page.Width*.77;foreach(Word w in page.GetWords()){if(w.BoundingBox.Left>=actionCutoff)continue;var a=new AgendaWord{Text=w.Text,X=w.BoundingBox.Left,Y=offset+(page.Height-w.BoundingBox.Top)};pageWords.Add(a);all.Add(a);}if(pageNo==1)date=FindDate(pageWords);offset+=page.Height;}}var brands=all.Where(w=>w.Text.Equals("RENAULT",StringComparison.OrdinalIgnoreCase)||w.Text.Equals("NISSAN",StringComparison.OrdinalIgnoreCase)).OrderBy(w=>w.Y).ToList();var result=new List<Appointment>();for(int i=0;i<brands.Count;i++){if(!brands[i].Text.Equals("RENAULT",StringComparison.OrdinalIgnoreCase))continue;double start=brands[i].Y-24;double end=brands[i].Y+155;if(i+1<brands.Count)end=Math.Min(end,brands[i+1].Y-25);var block=all.Where(w=>w.Y>=start&&w.Y<=end).ToList();var a=ParseBlock(block,brands[i],date);if(a!=null)result.Add(a);}return result;}
 string FindDate(List<AgendaWord>w){foreach(var l in Lines(w,0,400,-1,200)){string t=l.Text.ToLowerInvariant();if(Regex.IsMatch(t,@"\d{1,2}\s+de\s+[a-záéíóú]+\s+de\s+\d{4}")){var m=Regex.Match(t,@"(\d{1,2})\s+de\s+([a-záéíóú]+)\s+de\s+(\d{4})");var months=new Dictionary<string,int>{{"enero",1},{"febrero",2},{"marzo",3},{"abril",4},{"mayo",5},{"junio",6},{"julio",7},{"agosto",8},{"septiembre",9},{"octubre",10},{"noviembre",11},{"diciembre",12}};int mo;if(m.Success&&months.TryGetValue(m.Groups[2].Value,out mo))return m.Groups[1].Value.PadLeft(2,'0')+"/"+mo.ToString("00")+"/"+m.Groups[3].Value.Substring(2);}}return "";}
 Appointment ParseBlock(List<AgendaWord>w,AgendaWord brand,string date){var a=new Appointment{Fecha=date};var times=w.Where(x=>x.X<80&&Regex.IsMatch(x.Text,@"^\d{1,2}:\d{2}$")).OrderBy(x=>Math.Abs(x.Y-brand.Y)).ToList();if(times.Count==0)return null;a.Hora=times[0].Text;var clientLines=Lines(w,185,322,brand.Y-12,brand.Y+65);var names=new List<string>();foreach(var l in clientLines){string t=l.Text.Trim();string key=Tools.N(t);if(t.Contains("@")||Regex.IsMatch(t,@"\d{7,}")||key.Contains("RECORDAR")||key=="TURNO"||key=="HECHO")continue;if(Regex.IsMatch(t,@"[A-Za-zÁÉÍÓÚÑáéíóúñ]")&&t.ToUpperInvariant()==t)names.Add(t);}a.Cliente=String.Join(" ",names.ToArray()).Trim();foreach(var l in Lines(w,185,322,brand.Y-15,brand.Y+145)){string digits=Regex.Replace(l.Text,@"\D","");if(digits.Length>=7&&digits.Length<=22){a.Telefono=l.Text.Trim();break;}}
 var vehicle=Lines(w,315,395,brand.Y-5,brand.Y+150);var model=new List<string>();bool afterBrand=false;foreach(var l in vehicle){string t=l.Text.Trim();string compact=Regex.Replace(t,@"[^A-Za-z0-9]","");if(t.IndexOf("RENAULT",StringComparison.OrdinalIgnoreCase)>=0){afterBrand=true;t=Regex.Replace(t,"RENAULT","",RegexOptions.IgnoreCase).Trim();if(t.Length>0)model.Add(t);continue;}if(!afterBrand)continue;if(IsPlate(compact)){a.Patente=compact;break;}if(t.IndexOf("Número de chasis",StringComparison.OrdinalIgnoreCase)>=0||t.Equals("vehículo",StringComparison.OrdinalIgnoreCase))break;if(!Regex.IsMatch(t,@"^\d+\s*km"))model.Add(t);}a.Modelo=String.Join(" ",model.ToArray()).Trim();foreach(var l in vehicle){string c=Regex.Replace(l.Text,@"[^A-Za-z0-9]","");if(a.Patente.Length==0&&IsPlate(c))a.Patente=c;if(Regex.IsMatch(c,@"^[A-HJ-NPR-Z0-9]{17}$",RegexOptions.IgnoreCase))a.Chasis=c;}
 var services=Lines(w,395,460,brand.Y-8,brand.Y+150);var sv=new List<string>();foreach(var l in services){string t=l.Text.Trim();if(t.Length==0)continue;if(t.Equals("Servicios",StringComparison.OrdinalIgnoreCase))continue;sv.Add(t);}a.Servicio=String.Join(" ",sv.ToArray()).Trim();return a;}
 bool IsPlate(string s){return Regex.IsMatch(s,@"^[A-Z]{2}\d{3}[A-Z]{2}$",RegexOptions.IgnoreCase)||Regex.IsMatch(s,@"^[A-Z]{3}\d{3}$",RegexOptions.IgnoreCase);}
 void CompleteMotors(){string path=Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"vehiculos.dat");if(!File.Exists(path))return;var byVin=new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase);foreach(string line in File.ReadLines(path,Encoding.UTF8)){string[] p=line.Split('\t');if(p.Length!=7)continue;string vin=Tools.N(Tools.D(p[0]));string motor=Tools.N(Tools.D(p[6]));if(vin.Length>0&&motor.Length>0&&!byVin.ContainsKey(vin))byVin.Add(vin,motor.Length<=3?motor:motor.Substring(0,3));}foreach(var a in turns){string key=Tools.N(a.Chasis);string motor;if(key.Length>0&&byVin.TryGetValue(key,out motor))a.Motor=motor;}}
 void SetA4(){printer.DefaultPageSettings.Landscape=false;printer.DefaultPageSettings.PaperSize=new PaperSize("A4",827,1169);}
 List<AgendaLine> Lines(IEnumerable<AgendaWord> words,double xmin,double xmax,double ymin,double ymax){var result=new List<AgendaLine>();foreach(var w in words.Where(x=>x.X>=xmin&&x.X<xmax&&x.Y>=ymin&&x.Y<=ymax).OrderBy(x=>x.Y).ThenBy(x=>x.X)){AgendaLine line=result.LastOrDefault();if(line==null||Math.Abs(line.Y-w.Y)>3){line=new AgendaLine{Y=w.Y};result.Add(line);}line.Words.Add(w);}return result;}
 void ShowRows(){grid.Rows.Clear();foreach(var a in turns)grid.Rows.Add(a.Fecha,a.Hora,a.Cliente,a.Telefono,a.Modelo,a.Patente,a.Chasis,a.Motor,a.Servicio);host.UpdateBars();}
 void ShowPreview(){printIndex=0;using(var p=new PrintPreviewDialog{Document=printer,Width=1050,Height=760})p.ShowDialog();}
 void PrintNow(){using(var d=new PrintDialog{Document=printer})if(d.ShowDialog()==DialogResult.OK){printIndex=0;printer.Print();}}
 void ExportPdf(){string pdfPrinter="";foreach(string name in PrinterSettings.InstalledPrinters)if(name.Equals("Microsoft Print to PDF",StringComparison.OrdinalIgnoreCase)){pdfPrinter=name;break;}if(pdfPrinter.Length==0){MessageBox.Show("No se encontro la impresora 'Microsoft Print to PDF' de Windows.","Exportar PDF",MessageBoxButtons.OK,MessageBoxIcon.Warning);return;}string suggested="Turnos_de_Taller_"+TitleDate().Replace('/','-')+".pdf";using(var save=new SaveFileDialog{Filter="Archivo PDF (*.pdf)|*.pdf",Title="Guardar turnero como PDF",FileName=suggested,DefaultExt="pdf",AddExtension=true}){if(save.ShowDialog()!=DialogResult.OK)return;string oldPrinter=printer.PrinterSettings.PrinterName;bool oldPrintToFile=printer.PrinterSettings.PrintToFile;string oldFile=printer.PrinterSettings.PrintFileName;PrintController oldController=printer.PrintController;try{printer.PrinterSettings.PrinterName=pdfPrinter;printer.PrinterSettings.PrintToFile=true;printer.PrinterSettings.PrintFileName=save.FileName;printer.PrintController=new StandardPrintController();printIndex=0;printer.Print();MessageBox.Show("El turnero se exporto correctamente en:\n"+save.FileName,"PDF guardado",MessageBoxButtons.OK,MessageBoxIcon.Information);}catch(Exception ex){MessageBox.Show("No se pudo exportar el PDF.\n\n"+ex.Message,"Exportar PDF",MessageBoxButtons.OK,MessageBoxIcon.Error);}finally{try{printer.PrintController=oldController;printer.PrinterSettings.PrintToFile=oldPrintToFile;if(!String.IsNullOrEmpty(oldFile))printer.PrinterSettings.PrintFileName=oldFile;if(!String.IsNullOrEmpty(oldPrinter))printer.PrinterSettings.PrinterName=oldPrinter;}catch{}printIndex=0;}}}
 string TitleDate(){if(turns.Count==0)return "";string value=turns[0].Fecha.Trim();DateTime parsed;if(DateTime.TryParseExact(value,new[]{"dd/MM/yy","d/M/yy","dd/MM/yyyy","d/M/yyyy"},System.Globalization.CultureInfo.InvariantCulture,System.Globalization.DateTimeStyles.None,out parsed))return parsed.ToString("dd/MM/yyyy");return value;}
 void PrintPage(object sender,PrintPageEventArgs e){float left=e.MarginBounds.Left,top=e.MarginBounds.Top,width=e.MarginBounds.Width,bottom=e.MarginBounds.Bottom;var titleFont=new Font("Arial",16f,FontStyle.Bold);var normal=new Font("Arial",8f);var bold=new Font("Arial",8f,FontStyle.Bold);var small=new Font("Arial",7f);var format=new StringFormat{Trimming=StringTrimming.Word};string date=TitleDate();string title=date.Length>0?"Turnos de Taller - "+date:"Turnos de Taller";e.Graphics.DrawString(title,titleFont,Brushes.Black,left,top);float y=top+titleFont.GetHeight(e.Graphics)+10;e.Graphics.DrawLine(new Pen(Color.Black,1.5f),left,y,left+width,y);y+=4;while(printIndex<turns.Count){var a=turns[printIndex];float serviceWidth=width-55;float serviceHeight=e.Graphics.MeasureString(a.Servicio,normal,new SizeF(serviceWidth,1000),format).Height;float itemHeight=Math.Max(82f,62f+serviceHeight);if(y+itemHeight>bottom&&y>top+55)break;e.Graphics.DrawLine(Pens.Black,left,y,left+width,y);float xName=left+width*.09f,xVehicle=left+width*.55f,xPlate=left+width*.82f;e.Graphics.DrawString(a.Fecha,small,Brushes.Black,left,y+7);e.Graphics.DrawString(a.Hora,bold,Brushes.Black,left,y+23);e.Graphics.DrawString(a.Cliente,bold,Brushes.Black,new RectangleF(xName,y+6,width*.43f,28),format);e.Graphics.DrawString(a.Telefono,small,Brushes.Black,new RectangleF(xName,y+31,width*.40f,15),format);e.Graphics.DrawString(a.Modelo,bold,Brushes.Black,new RectangleF(xVehicle,y+6,width*.26f,32),format);e.Graphics.DrawString(a.Patente,bold,Brushes.Black,new RectangleF(xPlate,y+6,width*.10f,16),format);if(a.Chasis.Length>0)e.Graphics.DrawString(a.Chasis,small,Brushes.Black,new RectangleF(xVehicle,y+39,width*.38f,14),format);if(a.Motor.Length>0)e.Graphics.DrawString(a.Motor,bold,Brushes.Black,new RectangleF(left+width-62,y+37,34,16),format);e.Graphics.DrawString(a.Servicio,normal,Brushes.Black,new RectangleF(left+12,y+54,serviceWidth,serviceHeight+2),format);e.Graphics.DrawRectangle(Pens.Black,left+width-25,y+9,20,20);y+=itemHeight;printIndex++;}e.Graphics.DrawLine(Pens.Black,left,y,left+width,y);e.HasMorePages=printIndex<turns.Count;if(!e.HasMorePages)printIndex=0;format.Dispose();titleFont.Dispose();normal.Dispose();bold.Dispose();small.Dispose();}
}
}
